### PR TITLE
Improved UX.

### PR DESCRIPTION
**Pull request by FradSer**
Now you can use the template folder which its status is dro...pped. When all done the script now can set the status of folder to dropped automatic. **You can review your projects without template projects.**

### CODE REVIEW

**Comment by lemonmade** [comment]
The `.applescript` file is being treated as binary, so I can't actually review these changes :(

**Comment by FradSer** [comment]
`Templates.applescript` has converted to UTF-8.

**Comment by lemonmade** [comment]
Looks great, thanks!

**Comment by FradSer** [comment]
It's my pleasure to do.

**Pull request merged**
